"""
An alternating array is a list of any length in which two (not necessarily different)
values are alternating (all even-indexed items are equal, and all odd-indexed items are equal).
Given an array, return true if it is alternating.

Examples:

[]             -> True
[1]            -> True
[1,1]          -> True
[1,2,1]        -> True
[10,5,10,5,10] -> True
[2,2,3,3]      -> False
[5,4,3,5,4,3]  -> False
"""

def check_alternate(l):
    if len(l) <= 2:
        return True
    even_value = l[0]
    odd_value = l[1]
    for k,v in enumerate(l):
        if k % 2 == 0:
            # even idx
            if v != even_value:
                return False
        else:
            if v != odd_value:
                return False
            
    return True

if __name__ == "__main__":
    assert check_alternate([1,2,1]) == True
    assert check_alternate([10,5,10,5,10]) == True
    assert check_alternate([2,2,3,3]) == False
    assert check_alternate([5,4,3,5,4,3]) == False

    # ADDITIONAL TEST CASES GENERATED BY CHAT GPT #
    # Trivial cases
    assert check_alternate([]) == True
    assert check_alternate([42]) == True
    assert check_alternate([7, 7]) == True
    assert check_alternate([7, 8]) == True

    # Short arrays
    assert check_alternate([1, 2]) == True
    assert check_alternate([1, 2, 2]) == False
    assert check_alternate([1, 1, 2]) == False

    # Repetition patterns
    assert check_alternate([3, 3, 3, 3]) == True
    assert check_alternate([4, 5, 4, 5]) == True
    assert check_alternate([4, 5, 4, 6]) == False

    # Longer valid alternations
    assert check_alternate([0, 1, 0, 1, 0, 1]) == True
    assert check_alternate(["a", "b", "a", "b", "a"]) == True
    assert check_alternate([None, "x", None, "x"]) == True

    # Longer invalid alternations
    assert check_alternate([1, 2, 1, 2, 3]) == False
    assert check_alternate(["a", "b", "a", "c"]) == False
    assert check_alternate([True, False, True, True]) == False

    # Mixed types
    assert check_alternate([1, "1", 1, "1"]) == True
    assert check_alternate([1, "1", 2, "1"]) == False

    print("All tests passed")
