"""
Given a field represented as an array of 0s and 1s, where 1 means that 
position needs protection, you can place a scarecrow at any index, 
and each scarecrow protects up to k consecutive positions centered 
around itself (for example, for k = 3, a scarecrow at i protects i-1, i, and i+1). 
Return the minimum set of indices where scarecrows should be placed so 
that all the positions with 1 are protected. You can assume k is an odd number 
(or make up what happens if it's even).

Examples:

let field = [1, 1, 0, 1, 1, 0, 1];
let k = 3;

placeScarecrows(field, k);
> [1, 4, 6]

placeScarecrows([1, 0, 1, 1, 0, 1], k)
> [1, 4]

placeScarecrows([1, 1, 1, 1, 1], 1)
> [0, 1, 2, 3, 4]
"""
def placeScarecrows(field, k):
    protected = set()
    scarecrows = []

    field_len = len (field)
    i = 0
    while i < field_len:
        value = field[i]
        if value == 0 or i in protected:
            i += 1
            continue
        range_size = k // 2
        scarecrow_position = min(i + range_size, field_len - 1)
        scarecrows.append(scarecrow_position)
        protected.add(scarecrow_position)
        j = 0
        while j <= range_size:
            if 0 <= scarecrow_position + j < field_len:
                protected.add(scarecrow_position + j)
            if 0 <= scarecrow_position - j < field_len:
                protected.add(scarecrow_position - j)
            j += 1
        i = scarecrow_position + range_size + 1
    return scarecrows

if __name__ == "__main__":
    assert placeScarecrows([1, 1, 0, 1, 1, 0, 1], 3
    ) == [1, 4, 6]

    assert placeScarecrows([1, 0, 1, 1, 0, 1], 3) == [1, 4]

    assert placeScarecrows([1, 1, 1, 1, 1], 1) == [0, 1, 2, 3, 4]

    assert placeScarecrows([], 3) == []

    # Tests generated by ChatGPT
    # ✅ Edge case: no positions needing protection
    assert placeScarecrows([0, 0, 0, 0], 3) == []

    # ✅ Single position needing protection
    assert placeScarecrows([1], 3) == [0]

    # ✅ All positions need protection, k = 3
    # One scarecrow can protect 3 positions → positions 0–2, 3–5, etc.
    assert placeScarecrows([1, 1, 1, 1, 1, 1, 1], 3) == [1, 4, 6]

    # ✅ Sparse field — only first and last need protection
    assert placeScarecrows([1, 0, 0, 0, 0, 0, 1], 3) == [1, 6]

    # ✅ Even k (define behavior yourself, e.g., k=4 means protect 2 left + 1 right)
    assert placeScarecrows([1, 0, 1, 1, 0, 1], 4) == [2, 5]

    # ✅ Larger k — big protection radius
    assert placeScarecrows([1, 1, 0, 1, 0, 0, 1, 1, 1], 5) == [2, 8]

    print("All tests passed")