import random
'''
Given a positive integer n, write a function that returns an array containing all integers from 1 to n, 
where each integer i appears exactly i times in the result. 
For example, 3 should appear 3 times, 5 should appear 5 times, and so on. 
The order of the integers in the output array does not matter.

Example:

> repeatedIntegers(4)
> [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
'''
def repeated_integers(n):
    if n == 0:
        return []
    final_list = []
    for i in range(n + 1):
        final_list.extend([i] * i)
    return final_list

if __name__ == "__main__":
    assert sorted(repeated_integers(4)) == [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]

    # TEST CAESES GENERATED BY CHAT GPT#
    # Small inputs
    assert repeated_integers(0) == []                       
    assert repeated_integers(1) == [1]

    # Order does not matter → always sort
    assert sorted(repeated_integers(2)) == [1, 2, 2]
    assert sorted(repeated_integers(3)) == [1, 2, 2, 3, 3, 3]

    # Very small boundaries
    assert sorted(repeated_integers(1)) == [1]
    assert sorted(repeated_integers(2)) == [1, 2, 2]

    assert sorted(repeated_integers(5)) == [1, 
        2, 2, 
        3, 3, 3, 
        4, 4, 4, 4, 
        5, 5, 5, 5, 5
    ]

    assert len(repeated_integers(5)) == 1 + 2 + 3 + 4 + 5

    result_100 = repeated_integers(100)
    assert len(result_100) == 100 * 101 // 2                 # triangular number check
    assert result_100.count(100) == 100
    assert result_100.count(50) == 50

    for _ in range(20):
        n = random.randint(1, 2000)
        out = repeated_integers(n)
        # Size must equal n*(n+1)/2
        assert len(out) == n * (n + 1) // 2
        # Each i must appear exactly i times
        for k in range(1, n + 1):
            assert out.count(k) == k

    print("All tests passed")