'''
You are given two sorted arrays, a and b, where a has a large enough size buffer at the end 
to hold b (which can be spaces, zeroes, or nulls). Write a function to merge b into a in sorted order.

Example:

let a = [1, 3, 5, 0, 0, 0];
let b = [2, 4, 6];

> merge(a, b)
> [1, 2, 3, 4, 5, 6]
'''

def merge_first_solution(a, b):
    a_size = len(a)
    #iterarete over b to get number by number
    for candidate in b:
        inserted = False
        for k,v in enumerate(a):
            if v != 0 and v >= candidate:
                # move all elements of a with index bigger than k one step and set a[k]= candidate
                for j in range(a_size - 1, k, -1):
                    a[j] = a[j - 1]
                a[k] = candidate
                inserted = True
                break
        if inserted == False:
            # put the number in the last available space
            for k2,v2 in enumerate(a):
                if v2 == 0:
                    a[k2] = candidate
                    break
    return a

def merge(a, b):
    last_a_buffer = len(a) - 1
    last_b = len(b) - 1
    
    last_a = len(a) - len(b) - 1

    while last_a >= 0 and last_b >= 0:
        if a[last_a] >= b[last_b]:
            a[last_a_buffer] = a[last_a]
            last_a -= 1
        else:
            a[last_a_buffer] = b[last_b]
            last_b -= 1
        last_a_buffer -= 1

    while last_b >= 0:
        a[last_a_buffer] = b[last_b]
        last_b -= 1
        last_a_buffer -= 1
    return a
        

if __name__ == "__main__":
    
    assert merge([1, 3, 5, 0, 0, 0],[2, 4, 6] 
    ) == [1, 2, 3, 4, 5, 6]

    # TESTS GENERATED BY CHATGPT
    # All elements of b smaller than a
    assert merge([4, 5, 6, 0, 0, 0], [1, 2, 3]) == [1, 2, 3, 4, 5, 6]

    # All elements of b greater than a
    assert merge([1, 2, 3, 0, 0, 0], [4, 5, 6]) == [1, 2, 3, 4, 5, 6]

    # Interleaved elements
    assert merge([1, 4, 7, 0, 0, 0], [2, 5, 6]) == [1, 2, 4, 5, 6, 7]

    # Duplicate values
    assert merge([1, 3, 5, 0, 0, 0], [3, 3, 4]) == [1, 3, 3, 3, 4, 5]

    # Single-element arrays
    assert merge([1, 0], [2]) == [1, 2]
    assert merge([2, 0], [1]) == [1, 2]

    # Empty b (nothing to merge)
    assert merge([1, 2, 3], []) == [1, 2, 3]

    # a with buffer but empty b
    assert merge([1, 2, 3, 0, 0], []) == [1, 2, 3, 0, 0]

    # b with single large element
    assert merge([1, 2, 3, 0], [10]) == [1, 2, 3, 10]

    # b with single small element
    assert merge([2, 3, 4, 0], [1]) == [1, 2, 3, 4]

    # Basic interleaved merge
    assert merge([1, 3, 5, 0, 0, 0], [2, 4, 6]) == [1, 2, 3, 4, 5, 6]

    # Duplicates interleaved
    assert merge([1, 3, 3, 0, 0, 0], [3, 3, 4]) == [1, 3, 3, 3, 3, 4]

    # Uneven lengths (b shorter)
    assert merge([1, 4, 7, 0, 0], [2, 5]) == [1, 2, 4, 5, 7]

    # Uneven lengths (b longer)
    assert merge([3, 0, 0, 0], [1, 2, 4]) == [1, 2, 3, 4]

    # Large values
    assert merge([100, 200, 300, 0, 0, 0], [150, 250, 350]) == [100, 150, 200, 250, 300, 350]

    print("All tests passed!")

