"""
You are given a string consisting of lowercase words, each separated by a single space.

Determine how many vowels appear in the first word. Then, reverse each following word that has the same vowel count.

Examples:

flippedy("cat and mice")
> "cat dna mice"

flippedy("banana healthy")
> "banana healthy"
"""

def count_vowels(s):
    # consider only distinct vowels
    return len(set([l for l in s if l in ['a', 'e', 'i', 'o', 'u']]))

def flippedy(phrase: str):
    if not phrase:
        return ""
    
    splitted = phrase.split(" ")
    first = splitted[0]
    
    vowels_num = count_vowels(first)
    output = []
    if vowels_num == 0:
        return phrase
    for word in splitted[1:]:
        if count_vowels(word) == vowels_num:
            word = ''.join(reversed(word))
        output.append(word)        

    return " ".join([first] + output)


if __name__ == "__main__":
    print(flippedy("one two three four five"))
    assert flippedy("cat and mice") == "cat dna mice"
    assert flippedy("banana healthy") == "banana healthy"

    ### TEST CASES GENERATED BY CHAT GPT ###
    # Basic variations
    assert flippedy("a b c") == "a b c"
    # first word has 1 vowel, "b" and "c" have 0 → no reversals

    assert flippedy("ae io ou") == "ae oi uo"
    # first word has 2 distinct vowels; both following words match

    assert flippedy("cat dog pig") == "cat god gip"
    # cat → 1 vowel; dog → 1 vowel (reversed); pig → 1 vowel (reversed)

    # Repeated vowels vs distinct vowels
    assert flippedy("aaa bbb ccc") == "aaa bbb ccc"
    # first word has 1 distinct vowel; others have 0

    assert flippedy("aei aei aei") == "aei iea iea"
    # all words have same vowel count

    # Single-word input
    assert flippedy("hello") == "hello"
    # no following words to process

    # Words with no vowels at all
    assert flippedy("rhythm myths crypt") == "rhythm myths crypt"
    # vowel count = 0 for all

    # Trailing and leading spaces (if allowed by caller)
    assert flippedy("cat") == "cat"

    # Longer input
    assert flippedy("one two three four five") == "one two three ruof evif"

    # Edge behavior with empty string (depending on expectations)
    assert flippedy("") == "" 

    print("All test cases passed!")
